// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtymwospadqqbbgjqdqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0eW13b3NwYWRxcWJiZ2pxZHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDgxNDYsImV4cCI6MjA2NTgyNDE0Nn0.ub6krtY2I_EeJMwTJtTIb6mjad88vDNTg8BFAqMouSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);